#!/usr/bin/env python
#
import sys, cfecs

def print_usage():
    print ("Usage: \n"
           "   cfecs-update aws-region ecs_cluster ecs_service")

if __name__ == '__main__':

    if len(sys.argv) < 4:
        print_usage()
        sys.exit(1)

    region = sys.argv[1]
    cluster = sys.argv[2]
    service = sys.argv[3]

    cfecs.update_service(region, cluster, service)
